name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: zephyr-playground

      - name: Initialize
        working-directory: zephyr-playground
        run: |
          west init -l .
          west update

      - name: Build firmware
        working-directory: zephyr-playground
        run: |
          west build -b rpi_pico app

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: zephyr-playground/build/zephyr/zephyr.*
